name: Build Multi-Platform Geode Mod

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
        - name: macOS
          os: macos-latest
        - name: Android
          os: ubuntu-latest
          target: Android64

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main
      id: build
      with:
        # Crucial: Tells the action you intend to merge files later
        combine: true
        target: ${{ matrix.config.target }}

    - name: Upload Uncombined Artifact
      uses: actions/upload-artifact@v4
      with:
        name: geode-build-${{ matrix.config.name }}
        path: ${{ steps.build.outputs.build-output }}

  # A separate job to stitch all the platform builds together
  combine:
    name: Combine Builds
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4

    - name: Combine Artifacts
      uses: geode-sdk/build-geode-mod/combine@main
      id: combine

    - name: Upload Final Mod
      uses: actions/upload-artifact@v4
      with:
        name: final-geode-mod
        path: ${{ steps.combine.outputs.output }}
